
name: "Setup Node + Bun + Install Dependencies"
description: "Setup Node.js, Bun, and install project dependencies."
runs:
  using: "composite"
  steps:
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: 📦 Install Project Dependencies
      run: bun install --frozen-lockfile
      shell: bash