name: PR Preview Web

on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    type: deploy
    name: Deploy PR Preview
    environment: preview

  comment:
    needs: [deploy]
    type: github-comment
