name: Compress images
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"
  workflow_dispatch:

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
          ignorePaths: "node_modules/**,ios/**,android/**"

      - name: Create Pull Request
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v7
        with:
          title: 'chore: Optimize image assets using calibreapp/image-actions'
          branch-suffix: timestamp
          commit-message: 'chore: Optimize image assets using calibreapp/image-actions'
          body: ${{ steps.calibre.outputs.markdown }}