name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + pnpm + Install Dependencies
        uses: ./.github/actions/setup-node-pnpm-install

      - name: 🏃‍♂️ Run Oxlint
        uses: oxc-project/oxlint-action@v1

      - name: 🏃‍♂️ Run Oxfmt
        run: pnpm exec oxfmt src app --check
